In [2]:
import numpy as np

In [5]:
array = np.array([[1,2,3],
                  [2,3,4]])
print(array)
print('number of dim:',array.ndim)     #维度
print('shape:',array.shape)            #array的形状，几行几列
print('size:',array.size)              #元素个数

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


In [9]:
# 创建array 定义array的数据类型（type）
a = np.zeros((3,4))                   #全为 0 的数组
a = np.ones((3,4))  
a = np.arange(10,20,2)                # 10-20 步长为2
a = np.arange(12).reshape((3,4))      # reshape定义数组的形状
a = np.linspace(1,10,5)                  # 1-10 分五段 自动匹配数值
print(a)
a = np.array([2,23,4],dtype = np.int)    # np.float, np.int16, np.int32, np.int64, et.al
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
int32


In [8]:
# numpy 基础运算
a = np.array([10,20,30,40])
b = np.arange(4)
c = a + b
c = a - b
c = b**2
c = np.sin(a)            #三角函数，np.sin(), np.cos(), np.tan()

print(a,b)
print(c)

# 判断不等式
print(b)
print(b > 2)
print(b==2)

#矩阵运算
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))

c = a*b                          # 逐个相乘
c_dot = np.dot(a,b)              # 矩阵相乘
c_dot2 = a.dot(b)                # 矩阵相乘

print(c)
print(c_dot)
print(c_dot2)

# a = np.random.random((2,4))     # 生成0-1之间2*4的随机数组
a = np.arange(2,14).reshape((3,4))
print(a)
print(np.sum(a))                # 求和
print(np.sum(a,axis=1))        # 行求和，axis=0代表列，axis=1代表行
print(np.max(a))                # 求最大值
print(np.max(a,axis=0)) 
print(np.min(a))                # 求最小值
print(np.mean(a))               # 平均值  
print(np.median(a))             # 中位数
print(np.cumsum(a))             # 累加值
print(np.diff(a))               # 累差值 后一个数值减前一个 3*4 变成 3*3

a = np.arange(14,2,-1).reshape((3,4))
print(a)
print(np.sort(a))               # 逐行进行排序 
print(np.transpose(a))          # 矩阵转置 
print(a.T)                      # 矩阵转置 
print(np.clip(a,5,9))           # 矩阵中所有小于5的数赋值为5，所有大于9的数赋值为9

[10 20 30 40] [0 1 2 3]
[-0.54402111  0.91294525 -0.98803162  0.74511316]
[0 1 2 3]
[False False False  True]
[False False  True False]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
90
[14 30 46]
13
[10 11 12 13]
2
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [11]:
# numpy 索引
a = np.arange(3,15).reshape((3,4))

print(a)
print(np.argmin(a))           # 最小值的索引
print(np.argmax(a))           # 最大值的索引
print(a[2])                   # 索引第三行
print(a[:,1])                 # 索引第二列
print(a[1,1])                 # 索引第二行第二列

# 迭代数组的行
for row in a:
    print(row)
    
# 迭代数组的列
for column in a.T:
    print(column)
    
# 迭代数组的每个元素
print(a.flatten())        # 将数组变成序列
for item in a.flat:       # a.flat 为迭代器
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
0
11
[11 12 13 14]
[ 4  8 12]
8
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [14]:
# array合并
a = np.array([1,1,1])
b = np.array([2,2,2])

# a = a[:,np.newaxis]     # 列上加了一个维度，变成（3,1）的矩阵，a[np.newaxis,:]行上加维度,变成（1,3）矩阵
# b = b[np.newaxis,:]
# print(b,b.shape)

c = np.vstack((a,b))     # vertical stack 垂直（上下）合并
d = np.hstack((a,b))     # horizontal stack 水平合并

print(c,d)

c = np.concatenate((a,b,b,a),axis=0)    # 多个array合并，axis=0 为纵向合并，axis=1 为横向合并
print(c)
   

[[1 1 1]
 [2 2 2]] [1 1 1 2 2 2]
[1 1 1 2 2 2 2 2 2 1 1 1]


In [15]:
# array分割
a = np.arange(12).reshape(3,4)

print(np.split(a,2,axis =1))           # 2 代表分割成两份，axis=1列分割,横向分割，axis=0为行分割，纵向分割
print(np.array_split(a,3,axis =1))     # 不等份分割
print(np.vsplit(a,3))                  # 纵向分割
print(np.hsplit(a,2))                  # 横向分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [16]:
# numpy赋值
a = np.array([1,2,3])
b = a            # a与b关联，a改变b也改变，吧改变也会导致a改变
b = a.copy()     # deep copy  a的值赋值与b，但是不关联，相互的值改变不影响彼此
a[2]=11
print(a,b)

[ 1  2 11] [1 2 3]
